CLOUDINARY:
  CLOUD_NAME: "dajw2wgld"
  API_KEY: "993831697492311"
  API_SECRET: "cyZyQDwDslgwWJPX08bEF74sX_4"

GITHUB:
  REPO_OWNER: "HusPhil"
  REPO_NAME: "Project_DCTroy"
  REPO_TOKEN: "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" 

GOOGLE_CLOUD:
  TYPE: "service_account"
  PROJECT_ID: "project-dctroy-484813"
  PRIVATE_KEY_ID: "70c7c64a28ebf865756c43899af6c92e83d3ec61"
  PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDAYj7p5E+JFhw2
    sUmw9ZkwFThaWk0bONibXEWHUomysnpcBhbLbw6yLe8Zp4Irn3vZP+ktHp9K11C1
    gop1MfKf9AyeuEcl6bwagrKincsV6SSg8+WYhHnAkHO1Xnctpf8uf/KXUekjqp9b
    zTkZpn0Djkt2Cvt8oBcgelQySaUxMY7J+7+YiI4YUzHy2rRxF1opdBc5ZCbDBSdd
    zj8z+oZqj0bXWK+8LULy5I3Yc1BMzKMh4GRIZlhvwZlp9rrLInrkL4QmZ6pEQHWE
    XnEzkCWIJqoSMP2tKn3etWtr4ftFz5JZiA7iNja+nxnbDC9olpCYMOaJGRIWkZe8
    9NyXmiiRAgMBAAECggEAGPfnRcCC7hN3ipr3KcdboAObsmZL4ZTpepMULFxIUMVH
    NNBO1GJP3EzdM6LWNcaCHWUPufJifCUhGB2ezgJd2ef5B1R6r29Rds4FqdikNe4c
    pI24UP4d4Hce/VK1pwVcmXKzpR4ADcf5h2xFf+W9YzZsPCAaxEbxbslRn3aIFlp9
    hN152NxOF6TMrvMSGeSg/mSNcBTvZCLm4hJK1lEytpCjDozPFnX2pY8p3XOcJZyJ
    dq17mfJ3BKvjM6B6bCLkYY+/upiEXJob8fWXsKVJhhjDvepVtyxFzLTIhcvFdVOp
    PfGY3RunuSg+P6+wJxHNfJH5ENIpzbAKPctKQB/VjQKBgQDq00JS4n3gJTg+cJVa
    l63SAqOd972eseY913cAfApvR2RKl2+Vj608CFIO7zYpQ4vK5DeQMXAQu+t+DfQx
    oX6dj2r1jCkVChXbkj7qjOTO8dVHpszZSkl/6e6Bzj2GHh5Pwyo3emFBTk6VvBtO
    GNC7q4zFVNAcuZE/Kd/Jk/x6QwKBgQDRu0L9Qnjyy1wSkS02EHgFsB+GaPoRcz11
    7khUUfx6yZ34MN2lXfV8D3eyNX3qHKpsvGHHncmEGB1C6YdBLku2l4fFcKHWA4FL
    x8J5jSrTlLbMT/rhxml0jSIr7GOPQbkmC/PfprM8BfDNuLtARtru97aXKbGb6GDA
    LOe0siY2mwKBgGAuVX0TbdFQDWBtxo7Lj5N0J0X9gfotDYwI46IcLD319Nskeby9
    k4wCMHITgpCWLPzWSvfReAAyqDsCRiHJ7s1kP8ABP5ZxghBkL0bsnI8yuFPXuxHI
    /p/Y1iruqX50eZ/b5T/B7XHNPBzSZjCvs1ca5daxbWhGjXpckV/EMGZ3AoGAHGEe
    e26XNyNVXh3O5FXuJ7bhTSq/S8UwN9j6aI5/f43wljjmhQ3lvdfJ9o9ObnNajEQh
    ZwVu0zUAIKHA74z4KcjvUkQfYfovcLWjFxeHCAJDifn4lLxoYKEIUrE195iJGSDc
    6xJ/hku3fd7VV6k+zr8uMd4ubk5PaTGqWMUSbqkCgYBQmJBcgXOZ7UrSiQdcDyOv
    Jxashq+O7W1sHJe6Otnse712RLgQPD3b3TDLXvhVP91NdS4i89AuBa/K20fwvb8v
    o6yZamNaz9YhPH3CL/5dkdltrevXYnKUOvl3yaHKZ2vN9Az86onDKVmV0S2WvClx
    PPoSStWQSuy+C39z2kPnqQ==
    -----END PRIVATE KEY-----
  CLIENT_EMAIL: "experiment-result-saver@project-dctroy-484813.iam.gserviceaccount.com"
  CLIEND_ID: "115198326484752837000"
  AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
  TOKEN_URI: "https://oauth2.googleapis.com/token"
  AUTH_PROVIDER_X509_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
  CLIENT_X509_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/experiment-result-saver%40project-dctroy-484813.iam.gserviceaccount.com"
  UNIVERSE_DOMAIN: "googleapis.com"